aplicaciones/inicio/urls.py
from django.urls import path
from . import views
from aplicaciones.inicio.views import EmpleadoCreateView, EmpleadoListView, EmpleadoLoginView, ClienteLoginView, ClienteRegistroView, PerfilView, DashboardView
from django.contrib.auth.views import LogoutView
from .views import DashboardDataView, DashboardView
from templates.inicio import *
from templates.reserva import *

urlpatterns = [
    path('', views.index, name='index'),
    path('servicios/', views.index_servicio, name='index_servicio'),
    path('menu_admin_empleado/', views.menu_admin_empleado, name='menu_admin_empleado'),
    path('empleado_create/', EmpleadoCreateView.as_view(), name='empleado_create'),
    path('empleado_list/', EmpleadoListView.as_view(), name='empleado_list'), 
    path('empleado_edit/<int:pk>/', views.EmpleadoEditView.as_view(), name='empleado_edit'),  # Ruta para editar
    path('empleado_delete/<int:pk>/', views.EmpleadoDeleteView.as_view(), name='empleado_delete'),
    path('login_empleado/', EmpleadoLoginView.as_view(), name='login_empleado'),
    path('menu_empleado/', views.menu_empleado, name='menu_empleado'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registro/', ClienteRegistroView.as_view(), name='registro'),
    path('login/', ClienteLoginView.as_view(), name='login'),
    path('menu_cliente/', views.menu_cliente, name='menu_cliente'),
    path('perfil/', PerfilView.as_view(), name='perfil'),
    path('dashboard/api/', DashboardDataView.as_view(), name='dashboard_api'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
]

aplicaciones/reserva/urls.py
from django.urls import path
from .views import (CrearReservaView, 
                    ReservaConfirmadaView, 
                    ValidarRutView, 
                    CrearDisponibilidadView, 
                    ListarDisponibilidadView,
                    ReservaListClientesView,
                    MenuReservaView,
                    CrearDisponibilidadEmpleadoView,
                    ValidarRutEmpleadoView,
                    CalendarioReservasView,
                    ObtenerHorasDisponiblesView,
                    PagoConfirmadaView)
from . import views

app_name = 'reserva'

urlpatterns = [
    path('crear_reserva/', CrearReservaView.as_view(), name='crear_reserva'),
    path('reserva_confirmada/', ReservaConfirmadaView.as_view(), name='reserva_confirmada'),
    path('pago_confirmado/', PagoConfirmadaView.as_view(), name='pago_confirmado'),
    path('validar_rut/', ValidarRutView.as_view(), name='validar_rut'),
    path('mis_reservas/', ReservaListClientesView.as_view(), name='reserva_list_clientes'),
    path('crear_disponibilidad/', CrearDisponibilidadView.as_view(), name='crear_disponibilidad'),
    path('listar_disponibilidad/', ListarDisponibilidadView.as_view(), name='listar_disponibilidad'),
    path('menu_reserva/', MenuReservaView.as_view(), name='menu_reserva'),
    path('crear_disponibilidad_empleado/', CrearDisponibilidadEmpleadoView.as_view(), name='crear_disponibilidad_empleado'),
    path('validar_rut_empleado/', ValidarRutEmpleadoView.as_view(), name='validar_rut_empleado'),
    path('pagar/<int:reserva_id>/', views.PagarReservaView.as_view(), name='pagar_reserva'),
    path('calendario_reservas/', CalendarioReservasView.as_view(), name='calendario_reservas'),
    path('horas_disponibles/', ObtenerHorasDisponiblesView.as_view(), name='horas_disponibles'),
]

proyectotesis/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicaciones.inicio.urls')),
    re_path('', include('aplicaciones.reserva.urls')),
    re_path('', include('aplicaciones.servicio.urls')),
    re_path('', include('aplicaciones.abastecimiento.urls')),
    re_path('', include('aplicaciones.inicio.urls')),
]

aplicaciones/inicio/forms.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.views.generic import CreateView
from django.contrib.auth import authenticate
from django.contrib.auth.hashers import make_password
from django import forms
from .models import Empleado, Cliente

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = ['rut','nombre', 'apellido', 'correo_electronico', 'contrasena', 'cargo', 'salario']

    def __init__(self, *args, **kwargs):
        super(EmpleadoForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            # Si el empleado ya existe, hacer que rut sea de solo lectura
            self.fields['rut'].widget.attrs['readonly'] = True

class EmpleadoLoginForm(forms.Form):
    rut = forms.CharField(label="RUT", max_length=9, required=True)
    contrasena = forms.CharField(label="Contraseña", widget=forms.PasswordInput, required=True)

    def clean(self):
        cleaned_data = super().clean()
        rut = cleaned_data.get("rut")
        contrasena = cleaned_data.get("contrasena")

        # Validación de autenticación
        empleado = authenticate(rut=rut, password=contrasena)
        if not empleado:
            raise forms.ValidationError("Usuario o contraseña incorrectos.")
        return cleaned_data 
    

#CLIENTE

class ClienteRegistroForm(forms.ModelForm):
    contrasena = forms.CharField(widget=forms.PasswordInput, label="Contraseña")
    confirmar_contrasena = forms.CharField(widget=forms.PasswordInput, label="Confirmar Contraseña")
    
    class Meta:
        model = Cliente
        fields = ['rut', 'nombre', 'apellido', 'correo_electronico', 'contrasena']
    
    rut= forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'RUT sin puntos ni guion | si termian en K Utilize "0"'})
    )

    contrasena= forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Utilize Mayusculas, Minusculas, numeros y simbolos'})
    )


    def clean_rut(self):
        rut = self.cleaned_data.get('rut')
        if len(rut) > 9:
            raise forms.ValidationError("El RUT no puede tener más de 9 caracteres.")
        return rut

    def clean(self):
        cleaned_data = super().clean()
        contrasena = cleaned_data.get("contrasena")
        confirmar_contrasena = cleaned_data.get("confirmar_contrasena")
        
        if contrasena != confirmar_contrasena:
            raise forms.ValidationError("Las contraseñas no coinciden.")
        return cleaned_data


class ClienteLoginForm(forms.Form):
    rut = forms.CharField(max_length=9, label="RUT", required=True)
    contrasena = forms.CharField(widget=forms.PasswordInput, label="Contraseña", required=True)

    def clean_rut(self):
        rut = self.cleaned_data.get("rut")
        if len(rut) > 9:
            raise forms.ValidationError("El RUT no puede tener más de 9 caracteres.")
        return rut

    def clean(self):
        cleaned_data = super().clean()
        rut = cleaned_data.get("rut")
        contrasena = cleaned_data.get("contrasena")
        
        # Autenticación del cliente
        cliente = authenticate(rut=rut, password=contrasena)
        if not cliente:
            raise forms.ValidationError("Usuario o contraseña incorrectos.")
        return cleaned_data


class PerfilForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['rut', 'nombre', 'apellido', 'correo_electronico']

aplicaciones/inicio/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView,DeleteView, View
from django.contrib.auth import authenticate
from .models import Empleado, Cliente
from django.contrib import messages
from aplicaciones.inicio.forms import EmpleadoForm
from django.contrib.auth import login
from django.shortcuts import render, redirect
from aplicaciones.inicio.forms import EmpleadoLoginForm, ClienteLoginForm, ClienteRegistroForm, PerfilForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin



def index(request):
    return render(request, 'inicio/index.html')

def index_servicio(request):
    return render(request, 'inicio/index_servicio.html')


def menu_empleado(request):
    return render(request, 'inicio/menu_empleado.html')

class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = 'inicio/empleado_form.html'
    success_url = reverse_lazy('empleado_list') 

    def get_form_class(self):
        from .forms import EmpleadoForm  # Importación diferida aquí
        return EmpleadoForm
    
class EmpleadoListView(ListView):
    model = Empleado
    template_name = 'inicio/empleado_list.html'
    context_object_name = 'empleados'

class EmpleadoEditView(UpdateView):
    model = Empleado
    form_class = EmpleadoForm
    template_name = 'inicio/empleado_form.html'  # Usamos el mismo formulario que para crear
    success_url = reverse_lazy('empleado_list')  # Redirige a la lista de empleados después de la actualización

    def form_valid(self, form):
        # Lógica adicional para guardar el empleado
        empleado = form.save(commit=False)
        empleado.save()
        messages.success(self.request, "Empleado actualizado correctamente.")
        return redirect(self.success_url)
    
class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = 'inicio/empleado_delete.html'  # Plantilla para confirmar eliminación
    success_url = reverse_lazy('empleado_list')  # Redirige a la lista de empleados

    def delete(self, request, *args, **kwargs):
        # Aquí también puedes agregar lógica de confirmación si lo necesitas
        messages.success(self.request, "Empleado eliminado correctamente.")
        return super().delete(request, *args, **kwargs)
    

def menu_admin_empleado(request):
    return render(request, 'inicio/menu_admin_empleado.html')


class EmpleadoLoginView(View):
    def get(self, request):
        form = EmpleadoLoginForm()
        return render(request, 'inicio/login_empleado.html', {'form': form})

    def post(self, request):
        form = EmpleadoLoginForm(request.POST)
        if form.is_valid():
            rut = form.cleaned_data['rut']
            contrasena = form.cleaned_data['contrasena']

            # Autenticación de empleado usando RUT y contraseña
            empleado = authenticate(request, rut=rut, password=contrasena)

            if empleado is not None:
                login(request, empleado)
                print("Empleado autenticado y logueado")
                return redirect('menu_empleado')  
            else:
                form.add_error(None, "Usuario o contraseña incorrectos.")

        # Si el formulario no es válido o las credenciales son incorrectas
        return render(request, 'inicio/login_empleado.html', {'form': form})
    


    #CLIENTE

class ClienteRegistroView(View):
    def get(self, request):
        form = ClienteRegistroForm()
        return render(request, 'inicio/registro.html', {'form': form})

    def post(self, request):
        form = ClienteRegistroForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('login'))
        return render(request, 'inicio/registro.html', {'form': form})

class ClienteLoginView(View):
    def get(self, request):
        form = ClienteLoginForm()
        return render(request, 'inicio/login.html', {'form': form})

    def post(self, request):
        form = ClienteLoginForm(request.POST)
        if form.is_valid():
            rut = form.cleaned_data['rut']
            contrasena = form.cleaned_data['contrasena']

            # Verifica las credenciales del cliente
            cliente = authenticate(request, rut=rut, password=contrasena)

            if cliente is not None:
                login(request, cliente)
                return render(request, 'inicio/menu_cliente.html')
            else:
                form.add_error(None, "Usuario o contraseña incorrectos.")
        # Si el formulario no es válido o las credenciales son incorrectas
        return render(request, 'inicio/login.html', {'form': form})


class PerfilView(LoginRequiredMixin, View):
    login_url = '/login/'  

    def get(self, request):
        # Asegúrate de que el usuario esté autenticado antes de continuar
        if not request.user.is_authenticated:
            return redirect('login')  # Redirige a login si no está autenticado

        form = PerfilForm(instance=request.user)
        return render(request, 'inicio/perfil.html', {'form': form})

    def post(self, request):
        # Verifica si el usuario está autenticado
        if not request.user.is_authenticated:
            return redirect('login')  # Redirige a login si no está autenticado
        
        form = PerfilForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('menu_cliente')  # Redirige al menú cliente o donde necesites
        return render(request, 'inicio/perfil.html', {'form': form})



@login_required
def menu_cliente(request):
    form = PerfilForm(instance=request.user)
    return render(request, 'inicio/menu_cliente.html', {'form': form})

#DASHBOARD
from django.db.models import Count, Sum, F
from django.db.models.functions import TruncMonth
from django.http import JsonResponse
from aplicaciones.abastecimiento.models import Stock
from aplicaciones.reserva.models import Reserva, Agenda, Pago
from .models import Empleado
from aplicaciones.servicio.models import Servicio

class DashboardDataView(View):
    def get(self, request):
        try:
            # Indicador 1: Tasa de Ocupación
            tasa_ocupacion = (
                Reserva.objects.filter(estado_reserva='c').count() /
                Agenda.objects.filter(disponible=False).count()
            ) * 100

            # Indicador 2: Reservas por Servicio
            reservas_por_servicio = Reserva.objects.values('id_servicio__tipo_servicio').annotate(total=Count('id'))

            # Indicador 3: Tasa de Pago
            tasa_pago = (Pago.objects.filter(estado_pago='pagado').count() / Reserva.objects.count()) * 100

            # Indicador 4: Crecimiento de Reservas
            crecimiento_reservas = Reserva.objects.annotate(
                month=TruncMonth('id_agenda__fecha')
            ).values('month').annotate(total=Count('id'))

            # Indicador 5: Productos Más Utilizados
            productos_utilizados = Stock.objects.values('id_producto__nombre_producto').annotate(total_usado=Sum('cantidad_necesaria'))

            # Indicador 6: Costos por Servicio
            costos_por_servicio = Servicio.objects.annotate(
            costo_insumos=Sum(F('stock__cantidad_necesaria') * F('stock__id_producto__cantidad')),
            ).values('tipo_servicio', 'costo_insumos')

            # Respuesta JSON
            data = {
                'tasa_ocupacion': tasa_ocupacion,
                'reservas_por_servicio': list(reservas_por_servicio),
                'tasa_pago': tasa_pago,
                'crecimiento_reservas': list(crecimiento_reservas),
                'productos_utilizados': list(productos_utilizados),
                'costos_por_servicio': list(costos_por_servicio),
            }
            return JsonResponse(data, safe=False)
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)

class DashboardView(View):
    def get(self, request):
        return render(request, 'inicio/dashboard.html')

templates/inicio/empleado_edit.html
{% extends "inicio/menu_admin_empleado.html" %}

{% block content %}
  <h2>{% if object %}Editar{% else %}Crear{% endif %} Empleado</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{% if object %}Guardar cambios{% else %}Registrar Empleado{% endif %}</button>
  </form>
  <a href="{% url 'empleado_list' %}">Volver a la lista de empleados</a>
{% endblock %}

templates/inicio/menu_cliente.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Menú Cliente{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style_menu_servicio.css' %}">
    <style>
        .header-container {
            background-color: #ffffff;
            padding: 15px 0;
            width: 100%;
            box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 30px;
            text-align: center;
        }
        h1, h2, h3 {
            font-family: 'Arial', sans-serif;
            color: #117391;
            margin: 0;
        }
        h2 {
            margin-top: 10px;
        }
        .button-63, .button-cerrarsesion {
            align-items: center;
            background-image: linear-gradient(144deg, #117391, #16BFE8 50%, #D7D7D7);
            border: 0;
            border-radius: 8px;
            box-shadow: rgba(151, 65, 252, 0.2) 0 15px 30px -5px;
            box-sizing: border-box;
            color: #FFFFFF;
            display: flex;
            font-family: Phantomsans, sans-serif;
            font-size: 18px;
            justify-content: center;
            line-height: 1em;
            min-width: 140px;
            padding: 19px 24px;
            text-decoration: none;
            user-select: none;
            white-space: nowrap;
            cursor: pointer;
            margin: 15px 0;
        }
        .button-container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            gap: 20px;
            padding-top: 20px;
        }
        .linea-divisoria {
            width: 40%;
            height: 3px;
            background-image: linear-gradient(144deg, #ffffff, #16BFE8 50%, #ffffff);
            margin: 10px auto;
        }

        /* Contenedor principal centrado */
.profile-container {
    max-width: 800px;  /* Define un ancho máximo */
    margin: 0 auto;    /* Centra el contenedor horizontalmente */
    padding: 20px;     /* Espaciado interno */
    background-color: #f9f9f9;  /* Fondo claro */
    border-radius: 10px; /* Bordes redondeados */
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);  /* Sombra suave */
}

/* Títulos centrados */
.profile-container h2 {
    text-align: center;
    color: #333;  /* Color de texto oscuro */
    font-size: 24px;  /* Tamaño de fuente */
    margin-bottom: 10px;  /* Espaciado debajo del título */
}

/* Estilo de los párrafos */
.profile-container p {
    text-align: center;
    font-size: 16px;  /* Tamaño de fuente */
    color: #666;  /* Color de texto gris */
    margin: 5px 0;  /* Espaciado entre los párrafos */
}

/* Estilo para el formulario dentro del contenedor (si es necesario) */
.profile-container form {
    margin-top: 20px; /* Espaciado superior */
    display: flex;
    flex-direction: column; /* Organiza los elementos del formulario en columna */
}

.profile-container form input,
.profile-container form select,
.profile-container form textarea {
    padding: 10px;
    margin: 10px 0; /* Espaciado entre los campos */
    border-radius: 5px; /* Bordes redondeados */
    border: 1px solid #ddd; /* Borde sutil */
    font-size: 16px; /* Tamaño de fuente */
}

.profile-container form button {
    background-color: #4CAF50;  /* Fondo verde */
    color: white;  /* Texto blanco */
    padding: 10px 20px;  /* Espaciado interno */
    border: none;  /* Sin borde */
    border-radius: 5px;  /* Bordes redondeados */
    cursor: pointer;  /* Aparece el cursor de mano */
    font-size: 16px;  /* Tamaño de fuente */
    transition: background-color 0.3s ease;
}

.profile-container form button:hover {
    background-color: #45a049;  /* Cambia a un verde más oscuro cuando se pasa el cursor */
}

/* Centrar los botones dentro del contenedor */
.button-container {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 20px;
    padding-top: 20px;
}

    </style>
</head>
<body>
    <div class="header-container">
        <h1>Bienvenidos al menú de clientes CPD</h1>
    </div>

    <div class="profile-container">
    <h2>Perfil de {{ user.nombre }}</h2>
    <p>Datos del Usuario</p>
    <p>Nombre/apellido: {{ user.nombre }} {{ user.apellido }}</p>
    <p>RUT: {{ user.rut }}</p>
    <p>Correo: {{ user.correo_electronico }}</p>
    <form action="{% url 'logout' %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="button-cerrarsesion">Cerrar sesión</button>
    </form>
    </div>
        <div class="linea-divisoria"></div>
        <!-- Botón de crear reserva centrado con estilo -->
        <div class="button-container">
            <form action="{% url 'reserva:crear_reserva' %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="button-63">Crear Reserva</button>
            </form>
            <!-- Botón de ver reservas centrado con estilo -->
            <a href="{% url 'reserva:reserva_list_clientes' %}?rut={{ user.rut }}">
                <button type="button" class="button-63">Ver Mis Reservas</button>
            </a>
        </div>

</body>
</html>

templates/inicio/menu_empleado.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Menú Empleado</title>
    <link rel="stylesheet" href="{% static 'style_menu_servicio.css' %}">

    <style>
        /* Contenedor de header para el h1 */
        .header-container {
            background-color: #ffffff; /* Fondo blanco */
            padding: 15px 0;
            width: 100%;
            box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1); /* Sombra suave */
            margin-bottom: 30px; /* Espacio debajo del header */
            text-align: center;
        }

        /* Estilo del h1 */
        h1 {
            font-family: 'Arial', sans-serif;
            font-size: 2em;
            color: #117391;
            margin: 0;
        }

        .button-cerrarsesion {
            align-items: center;
            background-image: linear-gradient(144deg, #117391, #545151 50%, #645f5f);
            border: 0;
            border-radius: 8px;
            box-shadow: rgba(151, 65, 252, 0.2) 0 15px 30px -5px;
            box-sizing: border-box;
            color: #FFFFFF;
            display: flex;
            font-family: Phantomsans, sans-serif;
            font-size: 18px; /* Ajustar el tamaño para pantallas grandes */
            justify-content: center;
            line-height: 1em;
            min-width: 140px;
            padding: 19px 24px;
            text-decoration: none;
            user-select: none;
            white-space: nowrap;
            cursor: pointer;
            margin: 15px 0; /* Espaciado vertical entre botones */
        }

        .button-63 {
            align-items: center;
            background-image: linear-gradient(144deg, #117391, #16BFE8 50%, #D7D7D7);
            border: 0;
            border-radius: 8px;
            box-shadow: rgba(151, 65, 252, 0.2) 0 15px 30px -5px;
            box-sizing: border-box;
            color: #FFFFFF;
            display: flex;
            font-family: Phantomsans, sans-serif;
            font-size: 18px; /* Ajustar el tamaño para pantallas grandes */
            justify-content: center;
            line-height: 1em;
            min-width: 140px;
            padding: 19px 24px;
            text-decoration: none;
            user-select: none;
            white-space: nowrap;
            cursor: pointer;
            margin: 15px 0; /* Espaciado vertical entre botones */
        }

        .button-63:active,
        .button-63:hover {
            outline: 0;
        }

        @media (min-width: 768px) {
            .button-63 {
                font-size: 35px; /* Un tamaño ligeramente mayor para pantallas grandes */
                min-width: 180px;
            }
        }

        /* Estilo para pantallas pequeñas */
        @media (max-width: 767px) {
            .button-63 {
                width: 200%;
                font-size: 60px; /* Aumentar tamaño de la fuente en pantallas pequeñas */
                min-width: 300px; /* Hacer los botones más anchos */
                padding: 30px 40px; /* Aumentar el padding para hacer los botones más grandes */
            }
        }

        /* Estilo para organizar los botones en una columna */
        .button-container {
            display: flex;
            flex-direction: column; /* Cambiar a columna */
            justify-content: center;
            align-items: center;
            gap: 20px; /* Espacio entre los botones */
            padding-top: 95px; /* Ajusta el espacio desde arriba */
            z-index: 2;
        }

        .button-container a {
            width: 100%; /* Hacer que los botones ocupen el 100% del ancho del contenedor */
            max-width: 300px; /* Limitar el ancho máximo del botón */
            text-align: center;
        }

        .linea-divisoria {
            width: 40%; /* Ajusta el ancho según el tamaño deseado */
            height: 3px; /* El grosor de la línea */
            background-color: #000000; /* Color de la línea */
            background-image: linear-gradient(144deg, #ffffff, #16BFE8 50%, #ffffff);
            margin: 10px auto; /* Centra la línea y agrega margen vertical */
        }

        .profile-container {
            max-width: 800px;  /* Define un ancho máximo */
            margin: 0 auto;    /* Centra el contenedor horizontalmente */
            padding: 20px;     /* Espaciado interno */
            background-color: #f9f9f9;  /* Fondo claro */
            border-radius: 10px; /* Bordes redondeados */
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);  /* Sombra suave */
        }
        
        /* Títulos centrados */
        .profile-container h2 {
            text-align: center;
            color: #333;  /* Color de texto oscuro */
            font-size: 24px;  /* Tamaño de fuente */
            margin-bottom: 10px;  /* Espaciado debajo del título */
        }
        
        /* Estilo de los párrafos */
        .profile-container p {
            text-align: center;
            font-size: 16px;  /* Tamaño de fuente */
            color: #666;  /* Color de texto gris */
            margin: 5px 0;  /* Espaciado entre los párrafos */
        }
        
        /* Estilo para el formulario dentro del contenedor (si es necesario) */
        .profile-container form {
            margin-top: 20px; /* Espaciado superior */
            display: flex;
            flex-direction: column; /* Organiza los elementos del formulario en columna */
        }
        
        .profile-container form input,
        .profile-container form select,
        .profile-container form textarea {
            padding: 10px;
            margin: 10px 0; /* Espaciado entre los campos */
            border-radius: 5px; /* Bordes redondeados */
            border: 1px solid #ddd; /* Borde sutil */
            font-size: 16px; /* Tamaño de fuente */
        }
        
        .profile-container form button {
            background-color: #4CAF50;  /* Fondo verde */
            color: white;  /* Texto blanco */
            padding: 10px 20px;  /* Espaciado interno */
            border: none;  /* Sin borde */
            border-radius: 5px;  /* Bordes redondeados */
            cursor: pointer;  /* Aparece el cursor de mano */
            font-size: 16px;  /* Tamaño de fuente */
            transition: background-color 0.3s ease;
        }

    </style>
</head>
<body>
    <div id="background-wrap">
        <div class="bubble x1"></div>
        <div class="bubble x2"></div>
        <div class="bubble x3"></div>
        <div class="bubble x4"></div>
        <div class="bubble x5"></div>
        <div class="bubble x6"></div>
        <div class="bubble x7"></div>
        <div class="bubble x8"></div>
        <div class="bubble x9"></div>
        <div class="bubble x10"></div>
        <img src="{% static 'LOGO_CPD_PNG.png' %}" alt="Logo" width="520" height="310" 
             style="position: absolute; top: 50%; left: 50%; opacity: 0.7; transform: translate(-50%, -50%); z-index: 1;">
    </div>

    <!-- Contenedor del título tipo header -->
    <div class="header-container">
        <h1>Bienvenidos al menú de empleados CPD</h1>
    </div>


    <div class="profile-container">
    <h2>Perfil de EMPLEADO: {{ user.nombre }} {{ user.apellido }}</h2>
    <p>Datos del Usuario</p>
    <p>RUT: {{ user.rut }}</p>
    <p>Correo: {{ user.correo_electronico }}</p>
    <p>Cargo: {{ user.cargo }}</p>
    <form action="{% url 'logout' %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="button-cerrarsesion">Cerrar sesión</button>
    </form>
    </div>
    <div class="button-container">
        <a href="{% url 'dashboard' %}" class="button-63">Dashboard</a>
        <a href="{% url 'menu_principal' %}" class="button-63">Abastecimiento</a>
        <a href="{% url 'menu_admin_empleado' %}" class="button-63">Admin</a>
        <a href="{% url 'menu_servicio' %}" class="button-63">Servicio</a>
        <a href="{% url 'reserva:menu_reserva' %}" class="button-63">Agenda</a>
        <a href="/" class="button-63">Inicio</a>
    </div>
    <div>
    
    </div>
</body>
</html>